# Generated by Django 5.2.7 on 2025-11-15 04:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(help_text="Name of the level (e.g., 'Grade 10', 'Year 1')", max_length=100, unique=True)),
                ('level_type', models.CharField(choices=[('quiz', 'Quiz'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], help_text='Type of educational level', max_length=20)),
                ('code', models.CharField(help_text="Unique code for the level (e.g., 'G10', 'UG1')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the level', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is currently active')),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'ordering': ['level_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(default='SmartExams University', help_text='Institution name displayed throughout the system', max_length=200)),
                ('system_title', models.CharField(default='SmartExam Portal', help_text='System title displayed in header', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='System logo image', null=True, upload_to='system/logos/')),
                ('admin_email', models.EmailField(default='admin@smartexams.edu', help_text='Primary admin email for notifications', max_length=254)),
                ('support_email', models.EmailField(default='support@smartexams.edu', help_text='Support email for user inquiries', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', help_text='Contact phone number', max_length=20)),
                ('default_exam_duration', models.IntegerField(default=60, help_text='Default exam duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('default_passing_percentage', models.IntegerField(default=60, help_text='Default passing percentage threshold', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_max_attempts', models.IntegerField(default=3, help_text='Default maximum attempts allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('randomize_questions_default', models.BooleanField(default=True, help_text='Default: Randomize question order')),
                ('show_correct_answers_default', models.BooleanField(default=True, help_text='Default: Show correct answers after exam')),
                ('allow_question_review', models.BooleanField(default=True, help_text='Allow students to review questions before submitting')),
                ('commence_exam_immediately', models.BooleanField(default=False, help_text='Start exam immediately or allow manual start')),
                ('browser_restrictions', models.BooleanField(default=True, help_text='Enable browser restrictions during exams')),
                ('fullscreen_enforcement', models.BooleanField(default=True, help_text='Force full-screen mode during exams')),
                ('copy_paste_prevention', models.BooleanField(default=True, help_text='Disable copy-paste during exams')),
                ('right_click_disabled', models.BooleanField(default=True, help_text='Disable right-click menu during exams')),
                ('keyboard_shortcuts_disabled', models.BooleanField(default=False, help_text='Prevent keyboard shortcuts during exams')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ExamModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(help_text="Exam title/name/subject (e.g., 'Mathematics Grade 10')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the exam', null=True)),
                ('code', models.CharField(help_text="Unique exam code (e.g., 'MATH101', 'ENG201')", max_length=50, unique=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Exam duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('passing_score', models.IntegerField(default=60, help_text='Minimum score percentage to pass (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.IntegerField(default=1, help_text='Maximum number of attempts allowed per student', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('randomize_questions', models.BooleanField(default=True, help_text='Shuffle questions for each student')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Show correct answers after exam completion')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this exam is currently available to students')),
                ('level', models.ForeignKey(help_text='Academic level this exam is for', on_delete=django.db.models.deletion.PROTECT, related_name='exam_modules', to='core.level')),
            ],
            options={
                'verbose_name': 'Exam Module',
                'verbose_name_plural': 'Exam Modules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='core_exammo_code_c5b435_idx'), models.Index(fields=['level', 'is_active'], name='core_exammo_level_i_3ded28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(help_text="Student's full name", max_length=200)),
                ('student_id', models.CharField(blank=True, db_index=True, help_text='Unique student identifier used for login', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student account is active')),
                ('uploaded_via_bulk', models.BooleanField(default=False, help_text='True if student was added via bulk upload')),
                ('level', models.ForeignKey(help_text="Student's current academic level", on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.level')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['level', 'full_name'],
                'indexes': [models.Index(fields=['student_id'], name='core_studen_student_fa4380_idx'), models.Index(fields=['level', 'is_active'], name='core_studen_level_i_a3ff49_idx')],
            },
        ),
    ]
