# Generated by Django 5.2.7 on 2025-11-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exammodule',
            index=models.Index(fields=['title'], name='core_exammo_title_6aa0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['name'], name='core_level_name_cb7078_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['level_type'], name='core_level_level_t_180a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['is_active'], name='core_level_is_acti_09ba4c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='core_studen_full_na_d1f1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['institution_name'], name='core_system_institu_161653_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['system_title'], name='core_system_system__7ac9f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='exammodule',
            constraint=models.UniqueConstraint(fields=('title', 'level'), name='unique_exam_per_level'),
        ),
    ]
