# Generated by Django 5.2.7 on 2025-11-15 20:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exammodule_core_exammo_title_6aa0d5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt_number', models.IntegerField(default=1, help_text='Attempt number (1, 2, 3, etc.)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', help_text='Current status of the attempt', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the exam was started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the exam was completed', null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Total time taken in seconds', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score percentage (0-100)', max_digits=5, null=True)),
                ('total_questions', models.IntegerField(default=0, help_text='Total number of questions in the exam')),
                ('correct_answers', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('wrong_answers', models.IntegerField(default=0, help_text='Number of wrong answers')),
                ('unanswered', models.IntegerField(default=0, help_text='Number of unanswered questions')),
                ('passed', models.BooleanField(default=False, help_text='Whether the student passed the exam')),
                ('exam_module', models.ForeignKey(help_text='Exam being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.exammodule')),
                ('student', models.ForeignKey(help_text='Student taking the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.student')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('question_text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(help_text='Option A', max_length=500)),
                ('option_b', models.CharField(help_text='Option B', max_length=500)),
                ('option_c', models.CharField(help_text='Option C', max_length=500)),
                ('option_d', models.CharField(help_text='Option D', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='The correct answer option', max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Question difficulty level', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Question category or topic (optional)', max_length=100, null=True)),
                ('marks', models.IntegerField(default=1, help_text='Marks allocated to this question', validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer (optional)', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 for default ordering)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
                ('exam_module', models.ForeignKey(help_text='Exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.exammodule')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam_module', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text="Student's selected answer", max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When the answer was submitted')),
                ('exam_attempt', models.ForeignKey(help_text='The exam attempt this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.examattempt')),
                ('question', models.ForeignKey(help_text='The question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.question')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam_module'], name='core_examat_student_544781_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='core_examat_status_c2006b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('student', 'exam_module', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_module', 'is_active'], name='core_questi_exam_mo_fea19d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('exam_attempt', 'question')},
        ),
    ]
