# Generated by Django 5.2.7 on 2025-11-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examattempt_question_studentanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_type', models.CharField(choices=[('students', 'Students'), ('questions', 'Questions'), ('exams', 'Exams')], help_text='Type of data being uploaded', max_length=20)),
                ('file', models.FileField(help_text='Uploaded file', upload_to='bulk_uploads/%Y/%m/')),
                ('total_records', models.IntegerField(default=0, help_text='Total number of records in the file')),
                ('successful_records', models.IntegerField(default=0, help_text='Number of successfully processed records')),
                ('failed_records', models.IntegerField(default=0, help_text='Number of failed records')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='Error details and messages', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='Admin user who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload',
                'verbose_name_plural': 'Bulk Uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['upload_type', 'status'], name='core_bulkup_upload__32529a_idx'), models.Index(fields=['uploaded_by'], name='core_bulkup_uploade_874d2b_idx')],
            },
        ),
    ]
